[package]

name = "skeletal_animation_demo"
version = "0.0.1"
authors = ["Steve Jahns <s.t.jahns@gmail.com>"]

[[bin]]
name = "demo"
path = "src/main.rs"

[dependencies]
skeletal_animation = "0.6.0"
gfx_gl = "*"
env_logger = "*"
collada = "*"
vecmath = "*"
quaternion = "*"
dual_quaternion = "*"
gfx = "0.8.0"
gfx_device_gl = "0.7.0"
piston-gfx_texture = "*"
interpolation = "*"
piston-float = "*"
shader_version = "0.2.1"
sdl2 = "0.11.0"
pistoncore-sdl2_window = "0.20.0"
camera_controllers = "0.10.0"
piston = "0.16.0"
piston_window = "0.30.0"
gfx_text = "0.7.0"
gfx_debug_draw = "0.8.0"
dev_menu = "0.7.0"

